Throw an exception for Object children without @objc properties.
realm/realm-cocoa pull request #6844
Opened 2020-10-07 11:08 UTC by pavel-ship-it

2020-10-07 11:13 UTC, leemaguire requested changes
This needs a test

2020-10-07 11:13 UTC, leemaguire commented on CHANGELOG.md
> +* Throw an exception for Object children without @objc properties.
```suggestion
* Throw an exception for Objects that have none of its properties marked with @objc.
```

2020-10-07 11:13 UTC, leemaguire commented on Realm/RLMSchema.mm
> +        @throw RLMException(@"No properties was defined for '%@'. Did you remember to add '@obj' in your model?", schema.className);
```suggestion
        @throw RLMException(@"No properties are defined for '%@'. Did you remember to mark them with '@obj' in your model?", schema.className);
```

2020-10-07 11:55 UTC, pavel-ship-it commented
There is a problem @leemaguire - it will throw an exception before any test will start it's cycle.

2020-10-07 15:34 UTC, tgoyne commented
You can look at SchemaTests.mm to see examples of how we test schema errors. The basic idea is that they inherit from a different base class which won't be included in the default schema.

2020-10-07 15:36 UTC, tgoyne commented on Realm/RLMSchema.mm
> +    if ([cls shouldIncludeInDefaultSchema] && schema.isSwiftClass && schema.properties.count == 0) {
This isn't the right place for this check. It should go with the existing validation logic in RLMObjectSchema.mm.

2020-10-07 16:36 UTC, tgoyne commented on Realm/RLMObjectSchema.mm
> +        @throw RLMException(@"No properties are defined for '%@'. Did you remember to mark them with '@obj' in your model?", schema.className);
Missing the 'c' in `@objc`

2020-10-07 16:44 UTC, leemaguire approved these changes

2020-10-14 17:11 UTC, tgoyne approved these changes

2020-10-16 08:38 UTC, merged